language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - ci/Gemfile-rails-2-3
#  - ci/Gemfile-rails-3-0
  - ci/Gemfile-rails-3-1
  - ci/Gemfile-rails-3-2
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: ci/Gemfile-rails-2-3
